# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95bf621a899548330be5fc99b5ae83a35c128816f440dfa6c91876e3d7758bfc528bf65b20da07ca5bd32e77a8b11b29bff7e07b9b55bd5a84f00ba08be088f8

test:
  secret_key_base: 53ad3805f26c8d922af1e4d5e3120b3b23a0a96d13e1f1cd4b3c8b514217375c9a7fb148569ee8d7b165b6813bea21df616793c8a5dc422fff293a4b9e192bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
